---
title: "R Notebook"
output: html_notebook
---


```{r}
r<-function(x){
  return(round(x,2))
}
```


Coeficiente de correlacion
```{r}
x=c(20,40,20,30,10,10,20,20,20,30)
y=c(30,60,40,60,30,40,40,50,30,70)

xmenosmediax= x-mean(x)
xmenosmediay= y-mean(y)

sumatoria<-sum(xmenosmediay*xmenosmediax)

n=10

coefcorrelacion= sumatoria/((n-1)*sd(x)*sd(y))

coefcorrelacion



```


regresion lineal
```{r}
r=cor(y,x)

b0=r*sd(y)/sd(x)
b0

b1=mean(y)-b0*mean(x)
b1


```

regresion lineal simple= 1.18+18.94x



```{r}
x1=c(2,1,3,4)
y1=c(7,3,8,10)
```





Coef de determinacion
```{r}
coefdeterm<-function(x,y)
{
r1=cor(y,x)
cd=r1^2

cd
}

```



Error estandar de estimacion simple
```{r}
errorestandardsimple<-function(x,y)
{
b1=cor(y,x)*sd(y)/sd(x)
b1

b0=mean(y)-b1*mean(x)
b0

yprima=b0+b1*x
yprima

e=y1-yprima
e

n=4

errorestandar=((sum((e)^2))/(n-2))
return (errorestandar)
}


```

```{r}
errorestandardsimple(x1,y1)
```


```{r}
errorestimacionmultiple<-function(x,y,k)
{
  b1=cor(y,x)*sd(y)/sd(x)
b1

b0=mean(y)-b1*mean(x)
b0

yprima=b0+b1*x
yprima

e=y1-yprima
e

n=4

errorestandar=((sum((e)^2))/(n-(k-1)))
return (errorestandar)
}

```







```{r}
```


```{r}
x <- c(56,42,72,36,63,47,55,47,38,42)
y <- c(148,126,159,118,149,130,151,142,114,141)
plot(x,y)
summary(lm(x~y))
```





```{r}
cor(x,y)
cor(x,y)^2
```






