---
title: "R Notebook"
output: html_notebook
---
```{r}
library(xtable)
library(dplyr)
```

```{r}
Sangre<-as_tibble(list(
  Tipo=c("A+","B+","AB+","O+","A-","B-","AB-","O-"),Frecuencia=c(18.4,7.8,1.6,70.0,0.5,0.28,0.02,1.4)
  )
)
```
```{r}
Sangre <- cbind(Sangre, Prob = Sangre$Frecuencia/(sum(Sangre$Frecuencia)))
```

```{r}
r <- function(x){
  return(round(x,2))
}
```



```{r}
pos <- sum(Sangre[1:4,3])
neg <- 1 - pos
pos
neg
pos + neg
```

```{r}
r(dbinom(3, size=200, prob=Sangre[8,3]))
```
```{r}
r(200*Sangre[6,3])
```

```{r}
1 - Sangre[1,3]
```

```{r}
r(1/Sangre[8,3])
```

```{r}
200*Sangre[,3]
```

```{r}
pbinom(0, size=200, prob=Sangre[,3], lower.tail = FALSE)
200*Sangre[6,3]
```

```{r}
pbinom(0, size=200, prob=Sangre[,3], lower.tail = FALSE)
1/Sangre[,3]

```

```{r}
neg
abdn <- Sangre[7,3]/neg
abdn
```

```{r}
r(pbinom(0, size=10, prob = abdn, lower.tail = FALSE))
```

```{r}
Sangre
```

```{r}
op <- Sangre[4,3]/(Sangre[4,3] + Sangre[8,3])
bp <- Sangre[2,3]/(Sangre[2,3]+Sangre[6,3])
```


```{r}
r(dbinom(4, size=4, prob=op)*dbinom(1,size=1, prob=bp))
```

