---
title: "R Notebook"
output: html_notebook
---
```{r}
library(xtable)
library(dplyr)
```

```{r}
Sangre<-as_tibble(list(
  Tipo=c("A+","B+","AB+","O+","A-","B-","AB-","O-"),Frecuencia=c(18.4,7.8,1.6,70.0,0.5,0.28,0.02,1.4)
  )
)
```



```{r}
print(xtable(Sangre), type="html",include.rownames=FALSE)

```








```{r}
Sangre <- cbind(Sangre, Prob=Sangre$Frecuencia/(sum(Sangre$Frecuencia)))
```

```{r}
Sangre
```

```{r}
1 -sum(Sangre[1:4,3])
```

```{r}
r <- function(x){
  return(round(x, 2))
}
```


```{r}
r(dbinom(3, size = 200, prob = Sangre[5,3]))
```

```{r}
Sangre[6,3]*200
```

```{r}
r(1/Sangre[6,3])
```
```{r}
Sangre[,c(1,3)]
Sangre[5,3]*200

```



```{r}
r(pbinom(0, size = 200, prob = Sangre[,3], lower.tail = FALSE))
```

```{r}
Sangre[6,]
Sangre[6,3]*200
```

```{r}
1/(Sangre$Prob)
```

```{r}
r(pbinom(0,size=200, prob=Sangre[,3], lower.tail = FALSE))

```


```{r}
Sangre
```

```{r}
pos<-sum(Sangre[1:4,3])
pos
```

```{r}
neg <- 1 -pos
neg

```
```{r}
op <-(Sangre[4,3])/(Sangre[4,3]+Sangre[8,3])
op
```

```{r}
bp<-(Sangre[2,3])/(Sangre[2,3]+Sangre[6,3])
```


```{r}
r(dbinom(4, size=4, prob=op)*dbinom(1, size=1, prob=bp))

```


```{r}
r(pbinom(9, 190, prob = neg, lower.tail = FALSE))
```

