---
title: "Estadística - 2020-1"
output:
  html_document:
    df_print: paged
---
## P0 Pre Entrega
### **Sección:** 1.01
### **Profesor:** José Miguel Renom

**Alumno** | **Código** | **Líder**
-----------|------------|----------
Andrea Chu |201910124   |X
Juan Diego Chu|201920069|
Oscar Gómez|201910179   |
Joaquín Ramírez|201910277|
_El 5to integrante era Josué Carrillo, pero se retiró del curso_

Tenemos las siguientes propuestas para nuestro tema del proyecto:

1. **¿Cómo el cambio repentino a la educación virtual a distancia afecta el aprendizaje de los universitarios de UTEC?**

Ante la situación que vivimos actualmente a causa del COVID-19, la educación universitaria se ha visto  afectada. En muchos casos se ha hecho el cambio repentino a la educación virtual, como es el caso de UTEC, para que los alumnos no se detengan. Sin embargo, ¿este cambio garantiza el aprendizaje total? De esta manera, nos interesa indagar en los efectos que tiene el repentino cambio a la educación virtual en la vida de los alumnos de nuestra comunidad universitaria.

  * Puntos:
    + Presupuesto familiar
    + Rendimiento académico
    + Estabilidad emocional:
      + Personal
      + Familiar
    + Calidad de servicio:
      + Recursos de clases (material)
      + Capacidad de profesores 
  * Variables a medir:
    + Ingresos familiares
      + Ayuda financiera
      + Impedimentos de continuación de educación
    + Rendimiento académico:
      + Notas
      + Créditos
    + ¿El alumno siente que está aprendiendo o no?
    + Salud mental
      + Situación personal
      + Ambiente en casa
    + Calidad de servicio: 
      + ¿El profesor se adecuó bien?
      + ¿El curso funciona al 100% virtual como sería presencial?
    
2. **¿Cómo afecta la contaminación a la ciudad de Lima?**

Lima es considerada una de las ciudades más contaminadas en Latinoamérica. Las residentes de esta ciudad quizás ya están acostumbrados a ella, pero no es algo normal. Es interesante indagar los efectos que tiene la polución en distintas ámbitos del ecosistema limeño.

  * Puntos:
    + Escasez de agua debido a calentamiento global
    + Fuentes de agua contaminadas por desechos (río Rímac)
    + Smog en el aire
    + Ecosistemas destruidos que causan inundaciones/sequías
    + Radiación solar extrema
  * Variables a medir:
    + Variación de rango de temperaturas de Lima a lo largo de los años
    + Duración de temporadas de lluvias y huaicos y caudal de los ríos
    + Variación de radiación solar de Lima
    + Índice de CO2 en el aire
    + Días nublados/soleados al año
    
3. **¿Cuál es el impacto de la anemia en los niños peruanos?**

La anemia es una enfermedad que afecta a miles de personas en nuestro país, con mayor énfasis en las comunidades rurales. Dentro de este segmento de la población, los niños son quienes presentan la enfermedad constantemente. Sin duda es un problema que tiene que ser atendido a la brevedad, pero por el momento no hay mucha atención por parte de la sociedad.

  * Puntos:
    + Efecto económico
    + Mortalidad según el grado de anemia
    + Desarrollo infantil
    + Anemia como factor de riesgo frente a otras enfermedades
  * Variables a medir:
    + Costo económico en los últimos 10 años
    + Tipos de anemia con respecto a la tasa de mortalidad
    + Ámbitos que más afecta la anemia en el desarrollo durante la niñez
    + Presencia de otras enfermedades durante la anemia
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    