---
title: "R Notebook"
output:
  html_notebook: default
---
<b><h2>Estadística - 2020-1</h1></b>
<h3><b>Sección:</b> 1.01</h2>
<h3><b>Profesor:</b> José Miguel Renom</h2>
<style>table {font-family: arial, sans-serif;border-collapse: collapse;width: 100%;}td, th {border: 1px solid #dddddd; text-align: left; padding: 8px;}tr:nth-child(even) {  background-color: #dddddd;}</style>
<br>
<table>
<tr><th>Alumno</th><th>Código</th><th>Líder</th></tr>

<tr><td>Andrea Chu</td><td>201910124</td><td><b>X</b></td></tr>
<tr><td>Juan Diego Chu</td><td>201920069</td><td><b></b></td></tr>
<tr><td>Oscar Gómez</td><td>201910179</td><td><b></b></td></tr>
<tr><td>Joaquín Ramírez</td><td>201910277</td><td><b></b></td></tr>
</table>

El 5to integrante de nuestro grupo era Josué Carrillo, pero se retiró del curso.

<br>
<h4><b>Propuesta</b><h4>
<p>Para nuestro proyecto tenemos en mente los siguientes temas:</p>

<ol type="1">
  <li><b>¿Cómo el cambio repentino a la educación virtual a distancia afecta el aprendizaje de los universitarios?</b></li>
  Puntos:
  <ul>
  <li>Presupuesto familiar</li>
  <li>Rendimiento académico</li>
  <li>Estabilidad emocional: personal y familiar</li>
  <li>Calidad de servicio: recursos de clases y capacidad de profesores</li>
  </ul>
  Variables a medir:
  <ul>
  <li>Ingresos familiares</li>
  <li>Rendimiento académico: notas y créditos</li>
  <li>¿El alumno siente que está aprendiendo o no?</li>
  <li>Salud mental: situación personal y en casa</li>
  <li>Calidad de servicio: ¿el profesor se adecuó bien?</li>
  </ul>
  
  <li><b>¿Cómo afecta la contaminación al clima de Lima?</b></li>
  Puntos:
  <ul><li>Escazes de agua debido a calentamiento global</li>
  <li>Fuentes de agua contaminadas por desechos (río Rímac)</li>
  <li>Enfermedades a causa de contaminación del aire</li>
  <li>Ecosistemas destruidos causan inundaciones/sequías</li>
  <li>Radiación solar extrema</li>
  </ul>
  Variables a medir:
  <ul><li>Variación de rango de temperaturas de Lima a  lo largo de los años
</li>
  <li>Variación de radiación solar de Lima</li>
  <li>Contaminación del aire de Lima: índice de CO2</li>
  <li>Población con acceso a agua limpia</li>
  <li>Días nublados/soleados al año</li>
  </ul>
  <li><b>Anemia: el impacto económico en el Perú</b></li>
  Puntos:
  <ul>Efecto económico
  </ul>
</ol>